Repository RamakrushnaBiswal/PlayCafe, pull requests merged in 2024-10, with the labels that each got.

#17 Added the image given
  src/Components/Pages/Menu.jsx
  src/assets/Menu_assets/mega-creator.png
Labels: level 1, gssoc-ext

#24 warning removed
  src/Components/Shared/Footer.jsx
Labels: level 1, gssoc-ext

#15 Improvement: Making the Home page Images and text Responsive and visually appealing
  src/Components/Pages/About.jsx
  src/Components/Shared/Navbar.jsx
  src/Components/ui/Landing.jsx
  src/Components/ui/ReviewCarousel.jsx
  tailwind.config.js
  vite.config.js
Labels: level 2, gssoc-ext

#38 feat #27 added
  src/Components/Shared/Footer.jsx
  src/Components/Shared/footer/Content.jsx
  src/Components/Shared/footer/Footer.jsx
Labels: enhancement, level 2, gssoc-ext

#42 Added Backend Route for Café Reservation Form and .env Configuration
  backend/.env
  backend/.env.exapmle
  backend/.gitignore
  backend/controller/reservation.controller.js
  backend/index.js
  backend/models/reservation.model.js
  backend/package.json
  backend/routes/index.js
  backend/routes/reservationRouter.js
  frontend/package.json
  frontend/src/components/Pages/Register.jsx
Labels: enhancement, level 3, gssoc-ext

#47 Fixed the About and review carousel section
  frontend/src/components/Pages/About.jsx
  frontend/src/components/ui/ReviewCarousel.jsx
Labels: level 2, gssoc-ext, checked

#85 replaced the sip & play logo with new playcafe logo
  frontend/src/assets/Logo/playcafe.png
  frontend/src/components/Shared/Navbar.jsx
  frontend/src/components/Shared/footer/Content.jsx
Labels: enhancement, level 1, gssoc-ext

#83 enhancement:hamburger menu to toggle to 'X' on mobile
  frontend/src/components/Shared/Navbar.jsx
Labels: enhancement, level 1, gssoc-ext

#94 global message implemented
  frontend/package.json
  frontend/src/components/Shared/Navbar.jsx
Labels: enhancement, level 2, gssoc-ext

#131 Added social media icons in the footer
  frontend/index.html
  frontend/src/components/Shared/footer/Content.jsx
Labels: enhancement, level 1, gssoc-ext

#153 Added back to top button #151
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Shared/BackToTopButton.jsx
  frontend/tailwind.config.js
Labels: level 2, gssoc-ext

#164 Update ReviewCarousel.jsx
  frontend/src/components/ui/ReviewCarousel.jsx
Labels: bug, gssoc-ext

#130 Boardgame page: board games added and intruction feature, and added m…
  frontend/src/components/Pages/Boardgame.jsx
  package-lock.json
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#125 Implement Dynamic Event Management System
  README.md
  backend/controller/event.controller.js
  backend/models/events.model.js
  backend/routes/eventRouter.js
  backend/routes/index.js
  frontend/src/components/Pages/Event.jsx
Labels: level 3, gssoc-ext, hacktoberfest-accepted

#193 Add Multilingual Translator
  README.md
  frontend/src/assets/img/google.png
  frontend/src/components/Shared/GoogleTranslate.jsx
  frontend/src/components/Shared/footer/Content.jsx
Labels: enhancement, level3, gssoc-ext, hacktoberfest accepted

#233 Added splide js
  frontend/package.json
  frontend/src/components/Pages/Boardgame.jsx
  frontend/src/components/Pages/Signup.jsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#250 preloader and page transition added
  README.md
  frontend/src/App.jsx
  frontend/src/components/MainHOC.jsx
  frontend/src/components/Pages/Boardgame.jsx
  frontend/src/components/Pages/Event.jsx
  frontend/src/components/Pages/Home.jsx
  frontend/src/components/Pages/Menu.jsx
  frontend/src/components/Pages/Register.jsx
  frontend/src/components/Preloader.jsx
  frontend/src/main.jsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#264 added show/hide password
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/Signup.jsx
Labels: bug, level1, gssoc-ext

#260 Added password strength meter
  frontend/package.json
  frontend/src/components/Pages/Signup.jsx
Labels: enhancement, level2

#300 Integrate JWT Authentication with Passport-JWT for Secure User Authorization
  backend/config/passport.config.js
  backend/controller/admin.controller.js
  backend/controller/customer.controller.js
  backend/index.js
  backend/middlewares/authAdmin.js
  backend/package.json
  backend/routes/adminRouter.js
  backend/routes/customerRouter.js
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#307 Google/o auth
  README.md
  backend/.env.example
  backend/config/oauth.config.js
  backend/config/passport.config.js
  backend/config/secret.js
  backend/controller/googleOAuth.controller.js
  backend/index.js
  backend/middlewares/authAdmin.js
  backend/package.json
  backend/routes/customerRouter.js
  backend/routes/index.js
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/Signup.jsx
  frontend/src/components/Shared/Navbar.jsx
Labels: enhancement, level3, gssoc-ext, hacktoberfest accepted

#314 Added some env configuration
  backend/.env.example
  backend/config/oauth.config.js
  backend/config/secret.js
Labels: bug, level1, gssoc-ext, hacktoberfest accepted

#303 Fixed the responsiveness of the gif on Events page.
  README.md
  frontend/src/components/Pages/Event.jsx
Labels: bug, good first issue, level1, gssoc-ext, hacktoberfest accepted

#324 Fix duplicate CORS configuration and typo in errorMiddleware importUpdate index.js
  backend/index.js
Labels: bug, good first issue, level1, gssoc-ext

#288 Chore: fixed past date selection for reservation
  frontend/src/components/Pages/Register.jsx
Labels: bug, level1, gssoc-ext, hacktoberfest accepted

#334 Added google translator with more international language
  frontend/src/components/Shared/GoogleTranslate.jsx
  frontend/src/components/Shared/footer/Content.jsx
  frontend/src/components/Shared/footer/Google.jsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#352 chatbot has been added.
  frontend/index.html
  frontend/src/chatbot.jsx
  frontend/src/components/Shared/BackToTopButton.jsx
Labels: question

#348 Fix - UI enhancemend for Menu Page - Today's Special
  frontend/src/components/Pages/TodaysSpecial.jsx
Labels: bug, level1, gssoc-ext, hacktoberfest accepted

#366 Login/signup responsive
  frontend/src/components/Pages/About.jsx
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/Signup.jsx
  frontend/src/components/Shared/Navbar.jsx
  frontend/src/components/ui/Landing.jsx
Labels: let me know

#353 Created help page with FAQs
  frontend/src/components/Pages/HelpAndSupport.jsx
  frontend/src/components/Shared/footer/Content.jsx
  frontend/src/router/index.jsx
Labels: enhancement, level3, gssoc-ext, hacktoberfest accepted

#379 feat: Dark Mode
  README.md
  frontend/src/App.jsx
  frontend/src/components/Membership.jsx
  frontend/src/components/Pages/About.jsx
  frontend/src/components/Pages/Boardgame.jsx
  frontend/src/components/Pages/Event.jsx
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/Menu.jsx
  frontend/src/components/Pages/MenuPages.jsx/ThankPage/ThankPage.jsx
  frontend/src/components/Pages/Pages.jsx
  frontend/src/components/Pages/Register.jsx
  frontend/src/components/Pages/Signup.jsx
  frontend/src/components/Pages/TodaysSpecial.jsx
  frontend/src/components/Preloader.jsx
  frontend/src/components/Shared/Navbar.jsx
  frontend/src/components/Shared/footer/Content.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/components/ui/FeedbackForm.jsx
  frontend/src/components/ui/Landing.jsx
  frontend/src/components/ui/ReviewCarousel.jsx
  frontend/src/hooks/useDarkMode.js
  frontend/tailwind.config.js
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#375 Added Newsletter-Form
  CODE_OF_CONDUCT.md
  README.md
  backend/controller/event.controller.js
  backend/index.js
  backend/models/customer.model.js
  backend/models/events.model.js
  backend/routes/eventRouter.js
  frontend/package.json
  frontend/src/components/Pages/HelpAndSupport.jsx
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/Signup.jsx
  frontend/src/components/Shared/footer/Content.jsx
  frontend/src/router/index.jsx
Labels: level2, gssoc-ext, hacktoberfest accepted

#427 Restrict Event Booking to Verified Users
  README.md
  backend/controller/customer.controller.js
  backend/middlewares/authCustomer.js
  backend/routes/eventRouter.js
  frontend/src/components/Pages/Event.jsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest accepted

#424 Created TodaysSpecial Carousel Component
  frontend/package.json
  frontend/src/components/Pages/TodaysSpecial.jsx
Labels: enhancement, good first issue, level2, gssoc-ext, hacktoberfest accepted

#422 Update Themetoggle and Improve Footer Text Visibility
  frontend/src/components/Shared/footer/Content.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/index.css
Labels: pending

#426 feat/Improved Button Styles for Better Readability in both light & dark mode
  frontend/src/components/Pages/Event.jsx
Labels: pending
